import { Inter } from 'next/font/google'
import './globals.css'
import '../app/home.css'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Shyam - FrontEnd Developer Portfolio',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        type="text/css"
        charset="UTF-8"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
      />
      <body >{children}</body>
    </html>
  )
}
